export const MESSAGES = [
  { role: 'user', content: 'Hello!' },
  { role: 'assistant', content: 'Hi there!' },
  { role: 'user', content: 'How are you?' },
  { role: 'assistant', content: 'I am good, thanks! You?' },
  { role: 'user', content: 'I am great!' },
  { role: 'assistant', content: 'That’s awesome!' },
  { role: 'user', content: 'Tell me a joke.' },
  { role: 'assistant', content: 'Why did the chicken cross the road? To get to the other side!' },
  { role: 'user', content: 'Haha, nice one!' },
  { role: 'assistant', content: 'Glad you liked it!' },
  { role: 'user', content: 'What’s the weather like today?' },
  { role: 'assistant', content: 'I can’t check right now, but you can look outside!' },
  { role: 'user', content: 'Fair enough.' },
  { role: 'assistant', content: 'Anything else I can help with?' },
  { role: 'user', content: 'Tell me a fun fact.' },
  { role: 'assistant', content: 'Did you know octopuses have three hearts?' },
  { role: 'user', content: 'Wow, that’s cool!' },
  { role: 'assistant', content: 'Yeah, and their blood is blue too!' },
  { role: 'user', content: 'Mind blown!' },
  { role: 'assistant', content: 'Glad to surprise you!' },
]
